name: .NET 10 CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build da solução
        run: dotnet build --no-restore --configuration Release

      - name: Executar testes
        run: dotnet test --no-build --configuration Release --verbosity normal
